### ISSUE TITLE
Installation instructions line #2

### ISSUE THREAD

**Issue by apecity** [ss23/fortitoken-mobile-registration#4]
In my environment (Ubuntu 24.04.1 LTS, new install), the second line of the instructions ("pip install -r requirements.txt") results in this error:
"error: externally-managed-environment"

If I change the command to:
"venv/bin/pip install -r requirements.txt"

Then it works.  This may be a behavior specific to my installation environment, but I thought it might help someone else.

**Comment by ss23** [comment]
Sorry about this. This was a known issue in the install instructions. You just need to run the next line (`source ./venv/bin/activate`) first. The README should be updated to reflect the correct order to run the commands now.
