### ISSUE TITLE
Unable to install on Debian

### ISSUE THREAD

**Issue by FlavioB79** [ss23/fortitoken-mobile-registration#5]
Hi.
I'm facing following issue:

bonny@razor:~$ pip install -r requirements.txt
error: externally-managed-environment

I'm very noob here, so please bear with me... 
Thanks for your help already!

**Comment by ss23** [comment]
Sorry about this. This was a known issue in the install instructions. You just need to run the next line (`source ./venv/bin/activate`) first. The README should be updated to reflect the correct order to run the commands now.

**Comment by FlavioB79** [comment]
Hi Stephen.
Thanks for the super-fast reply and correction!
The setup has worked now - I'll now proceed with the rest.


Am Sa., 7. Dez. 2024 um 12:24 Uhr schrieb ☃ Stephen Shkardoon ☃ <
***@***.***>:
